---
title: "Ciencia de datos para políticas públicas"
subtitle: "Material para la clase"
format: html

author:
  - name: Elena Villalobos Nolasco
    orcid: 0009-0005-6389-291X
    email: villalobos_elena@tec.mx
    affiliations: Escuela de Gobierno y Transformación Pública


bibliography: slides/references.bib
---


## Generalidades del curso

- Las clases se repartirán entre teóría y práctica.
- Todo el contenido del curso se mostrará en esta página.
- Las tareas se entregarán y calificarán en **canvas**.
- Necesitas una computadora para la clase, no tablet. 
- Mi correo: [villalobos_elena@tec.mx](villalobos_elena@tec.mx)

## Materiales

::: {.callout-tip collapse="false"}
### 01: Introducción a la Ciencia de datos para políticas públicas

- Introducción a Ciencia de datos, IA y su relevancia en políticas públicas    
    - [Slides 01](slides/c01_intro.html) 

- Formulación de proyectos en Ciencia de datos
    - [Slides 02](slides/c02_project_scoping.html) 
:::

::: {.callout-tip collapse="false"}
### 02: Datos, adquisición, almacenamiento

- Tipos de datos, formato *tidy*, almacenamiento, retos de limipieza
    - [Slides 03](slides/c03_almacenamiento_rl.html) 

:::

::: {.callout-tip collapse="false"}

### 03: EDA y GEDA

- Estadísticas generales
- Principios de visualización
- Herramientas y técnicas de visualización de datos
    - [Slides 04](slides/c04_exploracion_formulacion.html) 

:::

::: {.callout-tip collapse="false"}

### 04: Aprendizaje de máquina supervisado

- Elementos de modelado para un problema de política pública:
    - Etiqueta, predictores
    - Línea base y tasa base
    - Validación Cruzada y Validación Temporal Cruzada
    - [Slides 05](slides/c05_supervisado_elementos.html) 
- Algoritmos
    - [Slides 06](slides/c06_supervisado_algoritmos.html) 
- Métricas
    - [Slides 07](slides/c07_supervisado_metricas.html) 


:::


::: {.callout-tip collapse="false"}

### 05: Aprendizaje de máquina no supervisado y NLP

- Algorítmos de aprendizaje no supervisado
    - [Slides 08](slides/c08_no_supervisado.html) 

- Introducción al procesamiento de lenguaje natural (NLP) para aplicaciones de política pública
    - [Slides 09](slides/c09_nlp_intro.html) 

:::


::: {.callout-tip collapse="false"}

### 06: Evaluación de resultados en proyectos de ciencia de datos para política pública.

- Ética
    - [Slides 10](slides/c10_etica.html) 
- Postmodelado y causalidad
    - [Slides 11](slides/c11_post_modelado.html) 

:::




## Políticas de la clase

- Suposición de que quieres aprender:
	- Asistencia importante.
	- Si necesitas faltar, avisar con anticipación y hacerte responsable de revisar el material visto.
	- **NO** se grabarán las clases.
	- **NO SE CALIFICARÁN TAREAS EXTEMPORÁNEAS**

#### Uso de IA generativa en la clase

- El uso de herramientas de IA generativa como ChatGPT, Claude, Gemini, entre otras, está permitido 
**únicamente** como apoyo para resolver dudas, entender errores y consultar conceptos, tratándolas como una forma de 
colaboración.
- Sin embargo, está **ESTRICTAMENTE PROHIBIDOO** pedir respuestas directas a ejercicios, copiar soluciones o utilizar 
agentes para resolver tareas de manera automática.

::: {.callout-important}
### Advertencia
**El uso de agentes o la entrega de trabajo generado como si fuera propio será considerado una falta de honestidad
 académica y se reportará a las autoridades correspondientes.**
:::

:::{.callout-note}
### Recomendaciones:
Antes de recurrir a un LLM:

- revisa la documentación oficial
- consulta los recursos compartidos en clase
- lee con atención la sintaxis, los errores y los resultados que arroje su programa
- escríbeme a mi correo
:::


## Evaluación


| Concepto                      | Porcentaje |
|-------------------------------|------------|
| Tareas                        | 60         |
| Evaluación intermedia         | 10         |
| Evaluación final              | 20         |
| Participación y lecturas      | 10         |

<br>

---

---

---

##### Nota:

<small>

Este curso está basado principalmente en:

- @solveforgood_platform, @dssg_fellowship, @dssg_ml_public_policy_lab, @rodolfaExperienceCenteredApproachTraining2019, @siegel2016predictive, @ianfosterBigDataSocial2021, @daume2017course, @james2023islp


</small>
