---
title: "Sesión técnica 2"
subtitle: "Flujo básico de trabajo: Git, Python y VS Code"
format:
  html:
    toc: true
    toc-depth: 2
    theme: cosmo
    highlight-style: github
date: today
---



En esta sesión aprenderemos un flujo básico para trabajar en proyectos de ciencia de datos.

La idea no es aprender todas las herramientas de Git, Python o la terminal, sino aprender **lo mínimo necesario para trabajar de manera ordenada y reproducible**.



# 1. Nuestro espacio de trabajo

Trabajaremos principalmente con cuatro herramientas:

- **Terminal**: para movernos entre carpetas y ejecutar comandos.
- **Git y GitHub**: para mantener versiones de nuestro trabajo.
- **VS Code**: para editar código y notebooks.
- **Python + uv**: para manejar Python y las dependencias de cada proyecto.

No necesitamos dominar todas estas herramientas.

Por ahora nos interesa entender cómo se conectan.

```python
Computadora
│
├── Terminal
│
├── Git
│
├── VS Code
│
└── Proyecto
    ├── notebooks/
    ├── data/
    ├── pyproject.toml
    └── uv.lock
```


## Trabajo básico desde la terminal

Dependiendo de tu sistema operativo estarás utilizando:

- **Windows:** PowerShell
- **macOS:** Terminal

Muchos de los comandos básicos que utilizaremos funcionan de forma similar en ambos sistemas.

- **¿Dónde estoy?**
    - Muestra la carpeta en la que estamos trabajando.
    ```bash
    pwd
    ```

- **Enlistar archivos**
    - Muestra los archivos y carpetas del directorio actual.
    ```bash
    ls
    ```

- **Cambiar de carpeta**
    - Para entrar a una carpeta:
    ```bash
    cd Documents
    ```
    ```bash
    cd nombre_carpeta
    ```
    
    - Para regresar una carpeta:
    
    ```bash
    cd ..
    ```
    

- **Crear una carpeta**

    ```bash
    mkdir proyectos
    ```
    
    Después podemos entrar:
    
    ```bash
    cd proyectos
    ```

## Instrucciones para la clase

Primero ve a la carpeta donde guardarás tus proyectos.

Por ejemplo:

```bash
cd Documents
mkdir repos_clases
cd repos_clases
```

Después clonamos el repositorio:

```bash
git clone <URL_DEL_REPOSITORIO>
```

Por ejemplo:

```bash
git clone git@github.com:LDataLab/intro-ds-eco.git
```

Git creará una carpeta con el contenido del repositorio.

Entramos al repositorio:

```bash
cd intro-ds-eco
```

Enlistamos lo que hay dentro del repositorio:


```bash
ls
```

Corremos la siguiente línea:

```bash
uv sync
```


Y abrimos Visual Studio:

```bash
code .
```

::: {.callout-important collapse="true"}
## Configurar usuario de Git

Antes de comenzar debemos indicar qué nombre queremos que aparezca en nuestros commits.

```bash
git config --global user.name "Tu Nombre"
```

También debemos configurar nuestro correo:

```bash
git config --global user.email "tu_correo@ejemplo.com"
```

Podemos verificar la configuración con:

```bash
git config --global --list
```

Esto solamente necesita hacerse una vez en cada computadora.

:::



# 2. Git y GitHub

Git y GitHub no son exactamente lo mismo.

- **Git** mantiene versiones de nuestros archivos en nuestra computadora.

- **GitHub** permite almacenar y compartir esos repositorios en internet.

```text
Tu computadora                    GitHub
----------------                  ----------------
Repositorio local   <---------->  Repositorio remoto
        Git                        Git + plataforma
```

Durante el curso utilizaremos ambos.



## Flujo escencial con git

Supongamos que hicimos un cambio en el archivo de exploracion, agregamos el cambio:

```bash
git add src/exploracion.py
```

Primero revisamos:

```bash
git status
```

Git nos mostrará los archivos nuevos o modificados, y si queremos ver qué cambio: 


```bash
git diff
```



### Seleccionar los cambios

```bash
git add src/exploracion_01.py
```

Después revisamos:

```bash
git status
```


### Crear un commit

Un **commit** registra una versión de nuestro proyecto.

```bash
git commit -m "Agrega exploración inicial de datos"
```

El mensaje debe describir brevemente qué hicimos.


### Subir cambios al repositorio

Para subir los a main

```bash
git push 
```


Uno de los comandos que más utilizaremos será:

```bash
git status
```

Este comando nos permite saber:

- en qué rama estamos;
- si modificamos archivos;
- si tenemos archivos nuevos;
- si hay cambios pendientes de guardar.

Por ejemplo:

```text
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

::: {.callout-tip}
## Una regla útil

Si no sabes qué está pasando con Git, no pruebes comandos al azar.

Primero ejecuta:

```bash
git status
```

y lee el mensaje.
:::


# 3. Trabajar en una rama

Una rama (branch) es una línea separada de trabajo dentro de un repositorio.

Sirve para hacer cambios sin modificar directamente la versión principal del proyecto, que normalmente está en `:w
main`.


```bash
git branch
```

Para crear una nueva rama y movernos a ella:

```bash
git switch -c nueva-rama
```

Ahora podemos verificar:

```bash
git status
```

Deberíamos observar algo similar a:

```text
On branch nueva-rama
```

Podemos experimentar y realizar cambios en nuestra rama sin modificar directamente `main`.


Para subir los cambios al repositorio:

```bash
git push -u origin nueva-rama
```


# 4. Python y ambientes virtuales

Los proyectos de Python normalmente necesitan paquetes adicionales.

Por ejemplo:

```text
pandas
matplotlib
seaborn
jupyter
```

El problema es que diferentes proyectos pueden necesitar diferentes paquetes o versiones.

Por eso utilizamos un **ambiente virtual**.

Podemos imaginarlo como una pequeña instalación de Python asociada únicamente a nuestro proyecto.

```text
Proyecto inegi
├── pandas
├── matplotlib
└── Python

Proyecto fiscal
├── pandas
├── scikit-learn
└── Python
```

Esto ayuda a que los proyectos sean:

- independientes;
- ordenados;
- reproducibles.

Durante este curso utilizaremos **uv** para administrar nuestros proyectos de Python.


## `pyproject.toml` y `uv.lock`

Nuestro proyecto tendrá dos archivos importantes:

```text
pyproject.toml
uv.lock
```

### `pyproject.toml`

Describe qué necesita nuestro proyecto.

Por ejemplo:

```text
pandas
matplotlib
seaborn
```

### `uv.lock`

Guarda las versiones exactas utilizadas.

Esto permite que otra persona pueda reproducir nuestro ambiente.

Estos archivos **sí deben guardarse en Git**.

::: {.callout-important}

La carpeta:

```text
.venv/
```

no debe subirse a GitHub.
:::


### Crear el ambiente del proyecto

Cuando ejecutamos:

```bash
uv sync
```

`uv` lee:

```text
pyproject.toml
uv.lock
```

y crea el ambiente necesario para ejecutar el proyecto.

Normalmente aparecerá una carpeta:

```text
.venv/
```

Nuestra estructura podría verse así:

```text
proyecto/
│
├── notebooks/
│   └── exploracion.ipynb
│
├── data/
│
├── pyproject.toml
├── uv.lock
└── .venv/
```


# 5. El flujo completo

El flujo que utilizaremos durante el curso puede resumirse así:

1. Ir al proyecto

```bash
cd mi-proyecto
```

2. Abrir VS Code

```bash
code .
```

3.  Hacer cambios en los archivos dentro de Visual Studio Code 

4. Revisar Git

```bash
git status
```


5. Seleccionar cambios

```bash
git add notebooks/exploracion.ipynb
```


6. Crear commit
```bash
git commit -m "Agrega análisis exploratorio"
```


7. Subir información al repositorio en lína

```bash
git push
```

8. Bajar información del repositorio en línea

```bash
git pull
```

# 6. Comandos útiles 

- Subir una rama nueva:

```bash
git push -u origin exploracion-datos
```

- Agregar dependencias si hacen falta

```bash
uv add pandas matplotlib
```

- Sincronizar el ambiente

```bash
uv sync
```

- Cambiar de ramas existentes
```bash
git swich rama
```

- Crear una nueva rama

```bash
git switch -c exploracion-datos
```



# 7. ¿Qué archivos subimos a GitHub?

Sí queremos subir:

```python
README.md
pyproject.toml
uv.lock
notebooks/
src/
```

Normalmente no queremos subir, que son archivos ocultos o de funcionamiento. Los puedes distinguir
porque comienzan con un `.` ó con `__`

```bash
.venv/
__pycache__/
.DS_Store
```

Para a Git que no suba estos archivos utilizamos:

```text
.gitignore
```


# 8. Idea para el trabajo en parejas

Para las siguientes actividades trabajaremos con **un repositorio por pareja**.

Una estructura mínima podría ser:

```bash
proyecto/
│
├── README.md
├── data/
├── notebooks/
│   └── exploracion.ipynb
│
├── pyproject.toml
├── uv.lock
└── .gitignore
```

Cada integrante podrá trabajar en una rama diferente.

Por ejemplo:

```text
main
├── exploracion-elena
└── exploracion-ana
```

Esto nos permitirá practicar:

- trabajar sobre un repositorio compartido;
- crear ramas;
- guardar cambios con commits;
- subir trabajo a GitHub;
- mantener un ambiente reproducible de Python.

Por ahora no necesitamos utilizar operaciones más avanzadas de Git.

---

# Para recordar

No necesitas memorizar todos los comandos.

Los cinco comandos de Git que utilizaremos constantemente son:

```bash
git status
git switch -c <rama>
git add <archivo>
git commit -m "mensaje"
git push
```

Y para Python:

```bash
uv add <paquete>
uv sync
```

Nuestro objetivo será acostumbrarnos gradualmente a este flujo de trabajo.
